# Yarn v3 configuration
nodeLinker: node-modules

# Enable better performance
compressionLevel: mixed
networkConcurrency: 50

# Cache settings
enableGlobalCache: false

# Compatibility settings
packageExtensions:
  "prop-types@*":
    dependencies:
      react: "*"
